### ISSUE TITLE
Suggestion to rename this package

### ISSUE THREAD

**Issue by enov** [kohana/cascading-filesystem#2]
I wanted at first to suggest to name this package just "kohana", since from this will come the main object that will control our modules, and this is where the CFS is defined.

However, since the name is already taken by our skeleton application, I thought maybe we can name this thing **Kohanzee** the module manager. The name is a combination of Kohana and the sister project Ohanzee, which is basically a collection of modules.

**Comment by lenton** [comment]
What about "cascading-filesystem"?

The cascading filesystem is the core of what this package represents, the autoloading and initialisation are just an extension to create what we call a "module". In the future, I see Kohana dropping the idea of a module completely and moving to "composer packages". However, I think the cascading filesystem will still be valuable resource for media files, configuration, etc. so that can remain without any repository name changes necessary.

**Comment by enov** [comment]
> What about "cascading-filesystem"?

Hmm... I like it. Maybe just "CFS"?

**Comment by enov** [comment]
or "cfs" (lowercased)

**Comment by lenton** [comment]
I worry that "cfs" wouldn't be as informative or self-explanatory.

**Comment by acoulton** [comment]
+1 for cascading-filesystem. It's infuriating reading composer.jsons or searching packagist and finding packages where you can't tell what they actually are...

**Comment by lenton** [comment]
@shadowhand Could you rename this repository to "cascading-filesystem" please.

**Comment by shadowhand** [comment]
@lenton done!
